# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('tcid', models.CharField(max_length=30)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('detail', models.TextField()),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
